### PR TITLE
Add Typescript support and partial conversion

### PR DESCRIPTION
**Pull request by mythmon**
Depends on #52. Once that is merged we can re-target this PR to the main branch.

### CODE REVIEW

**Comment by mythmon** [comment]
This should be ready to be reviewed now.

**Comment by Errolyn** [comment]
hmm I was waiting for the checks to run, but they haven't yet which is weird :/

**Comment by mythmon** [comment]
I suspect you have the setting on that doesn't run CI for PRs.

**Review by Errolyn — APPROVED** [review]
Everything looks good!

**Pull request merged**
